language: java
dist: trusty

jdk:
- openjdk8

services:
- rabbitmq

before_script:
- sudo rabbitmqctl add_vhost test1.rabbitmq.budjb.com
- sudo rabbitmqctl add_vhost test2.rabbitmq.budjb.com
- sudo rabbitmqctl set_permissions -p test1.rabbitmq.budjb.com guest ".*" ".*" ".*"
- sudo rabbitmqctl set_permissions -p test2.rabbitmq.budjb.com guest ".*" ".*" ".*"

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
