---
grails:
    profile: web
    codegen:
        defaultPackage: com.budjb.rabbitmq.test
    spring:
        transactionManagement:
            proxies: false
    gorm:
        # Whether to autowire entities.
        # Disabled by default for performance reasons.
        autowire: false
        reactor:
            # Whether to translate GORM events into Reactor events
            # Disabled by default for performance reasons
            events: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
endpoints:
    jmx:
        unique-names: true

---
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password: ''

environments:
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE

rabbitmq:
    host: localhost
    port: 5672
    user: guest
    password: guest
    connections:
      - name: connection1
        host: localhost
        username: guest
        password: guest
        virtualHost: test1.rabbitmq.budjb.com
        isDefault: true

      - name: connection2
        host: ${rabbitmq.host}
        username: ${rabbitmq.user}
        password: ${rabbitmq.password}
        virtualHost: test2.rabbitmq.budjb.com

    exchanges:
      - name: topic-exchange
        type: topic
        autoDelete: true
      - name: sub-topic-exchange
        type: topic
        autoDelete: true
        exchangeBindings:
            - exchange: topic-exchange
              binding: 'com.budjb.exchange.#'

    queues:
      - name: message-context
        autoDelete: true
        connection: connection1

      - name: message-converter
        autoDelete: true
        connection: connection1

      - name: reporting
        autoDelete: true
        connection: connection1

      - name: sleeping
        autoDelete: true
        connection: connection1

      - name: string-test
        autoDelete: true
        connection: connection1

      - name: topic-queue-all
        autoDelete: true
        binding: '#'
        connection: connection1
        exchange: topic-exchange

      - name: topic-queue-subset
        autoDelete: true
        binding: 'com.budjb.#'
        connection: connection1
        exchange: topic-exchange

      - name: topic-queue-specific
        autoDelete: true
        binding: com.budjb.rabbitmq
        connection: connection1
        exchange: topic-exchange

      - name: connection2-queue
        autoDelete: true
        connection: connection2

      - name: topic-queue-sub-exchange-set
        autoDelete: true
        binding: 'com.budjb.exchange.queue'
        connection: connection1
        exchange: sub-topic-exchange

      - name: topic-queue-sub-exchange-unused
        autoDelete: true
        binding: 'com.budjb.exchange.unused'
        connection: connection1
        exchange: sub-topic-exchange
